export const endPoints = {
  //---------------Auth Routes

  SIGNUP: "/register",
  SIGNIN: "/login",
  LOGOUT: "/auth/logout",
  EMAIL_VERIFY: "/email-verification",
  ORGANIZATION_CATEGORIES: "/organizationcategories",
  OTP_VERIFY: "/otpVerification",
  FORGET_PASSWORD: "/Verifyemailforgotpassword",
  FORGET_VERIFY: "/forgotpassword",
  ORGANIZATION_LOGO: "/uploadimage",
  ORGANIZATION_CREATE: "/createorganization",
  LOGO_DELETE: "/deleteimage",
  SELECT_DEPARTMENTS: "/SelectDepartment",
  GET_DEPARTMENTS: "/getSelectDepartment",
  CONFIRM_DEPARTMENTS_DESIGNATIONS: "/SelectedDepartmentsDesignation",
  GET_COUNTRIES: "/countriesData",
  GET_STATES: "/statesData",
  GET_CITIES: "/citiesData",
  CREATE_DEPARTMENT: "/departments",
  DESIGNATIONS: "/designations",
  GET_DESIGNATION: "/getDesignation",
  EMPLOYEES: "/employees",
  ADD_EMPLOYEES: "/createEmployee",
  VIEW_EMPLOYEES: "/viewEmployee",
  DELETE_EMPLOYEE: "/deleteEmployee",
  CREATE_DESIGNATION: "/designations",

  GET_EMPLOYEE: "/responsibleperson",
  GET_PERMISSION: "/employeePermission",
  APPLY_JOBS: "/applyjob",
  EDIT_EMPLOYEES: "/createEmployee",
  VIEW_EMPLOYEE_BYID: "/viewEmployee",
  UPDATE_EMPLOYEE: "/updateEmployee",

  JOBS: "/jobs",
  JOB_SEARCH_TAG: "/jobtags",
  CREATE_JOB: "/jobs",
  DEPARTMENT: "/departments",
  VIEWJOB: "/jobs",
  DELETEJOB: "/jobs",
  JOBAPPLICANTS: "/jobapplicants",
  JOBDETAILS: "/jobs",
  EDITJOB: "/jobs/edit",
  GET_MODULE: "/modules",

  UPDATE_USERROLE: "/updateDesignation",

  //---------------Auth Routes--------------------
};
