export const routeNames = {
  //public route names
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  RESETOTP: "/passwordotp",
  OTPVERIFY: "/otpverification",
  RESETPASSWORD: "/resetpassword",
  FORGOTPASSWORD: "/forgetpassword",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  //-----------Public--------------
  START: "/",
  NOTFOUND: "*",
  EMPLOYEES: "/employees",
  ADD_EMPLOYEE: "/employees/create",
  EDIT_EMPLOYEE: "/employees/edit",
  INITIAL: "/welcome",
  USER_ROLE: "/userrole",
  VIEW_ORGANIZATION: "organization",
  SELECT_DEPARTMENT: "/SelectDepartment",
  EDIT_DEPARTMENT: "/EditDepartment",
  SELECT_PERMISSION: "/selectpermission",
  ADDITIONAL_CHARGE: "/employeeRestrictions",
  CREATE_ORGANIZATION: "organization/create",
  NEW_APPLICATION: "/application/newapplication",
  VIEW_SUBMIITED_APPLICATIONS: "/application/submitted",
  CREATE_JOB: "/jobs/create",
  VIEWJOB: "/jobs",
  CREATE_EMPLOYEE: "/createEmployee",
  JOBDETAILPAGE: "/detailPage",
  JOBACCEPTPAGE: "/AcceptJob",
  CREATE_REQUIREMENTS: "/createRequirments",
  FLOWPAGE: "/flowpage",
  EDITJOB: "/jobs/edit",
  DATAFLOW: "/DataVisualizaion",
};
