export const routeNames = {
  //public route names
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  RESETOTP: "/passwordotp",
  OTPVERIFY: "/otpverification",
  RESETPASSWORD: "/resetpassword",
  FORGOTPASSWORD: "/forgetpassword",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  //-----------Public--------------
  START: "/",
  NOTFOUND: "*",
  ADD_EMPLOYEES: "/addemployees",
  VIEW_EMPLOYEES: "/viewemployee",
  INITIAL: "/welcome",
  USER_ROLE: "/userrole",
  VIEW_ORGANIZATION: "organization",
  SELECT_DEPARTMENT: "/SelectDepartment",
  EDIT_DEPARTMENT: "/EditDepartment",
  SELECT_PERMISSION: "/selectpermission",
  ADDITIONAL_CHARGE: "/employeeRestrictions",
  CREATE_ORGANIZATION: "/createorganization",
  NEW_APPLICATION: "/newapplication",
  VIEW_SUBMIITED_APPLICATIONS: "/submittedapplications",
  CREATE_JOB: "/createjob",
  VIEWJOB: "/viewjob",
  CREATE_EMPLOYEE: "/createEmployee",
  JOBDETAILPAGE: "/detailPage",
  JOBACCEPTPAGE: "/AcceptJob",
  CREATE_REQUIREMENTS: "/createRequirments",
  FLOWPAGE: "/flowpage",
  EDITJOB: "/editjob",
  DATAFLOW: "/DataVisualizaion",
};
