import "./globals.css";
import { NextAuthProvider } from "./providers";
import { Providers } from "./redux/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NextAuthProvider>{children}</NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
