/** @format */
export const Labels = {
  LOGIN: "Login",
  SIGN_UP: "Sign Up",
  USERNAME: "Username",
  EMAIL: "Email Address",
  EMAIL_USERNAME: "Email or Username",
  PASSWORD: "Password",
  NEWPASSWORD: "New Password",
  CONFIRMPASS: "Confirm Password",
  CONFIRMNEWPASS: "Confirm New Password",
  TYPE: "User Type",
  ORGANIZATION: "Organization",
  ADDRESS: "Address",
  CATEGORY: "Category",
  PLAN: "Subscription Plan",
  DOMAIN: "Domain & URL",
  ESTABLISHED_YEAR: "Established Year",
  PHONE_NO: "Contact No",
  ORGANIZATION_NAME: "Enter your organization Name",
  ORGANIZATION_CATEGORY: "Select your organization Category",
  ZIP_CODE: "Enter Zip Code",
  COUNTRY: "Select Country",
  STATE: "Select State",
  CITY: "Select City",
  ORG_EMAIL: "Enter organization Email ",
  ORG_PHONE: "Enter organization Phone No",
  ORG_DOMAIN: "Enter Domain Name",
  CREATE_ORGANIZATION: "Create Organization",
  REGISTER: "Register & Next",
  SIGIN_HEADING: "Welcome Back !",

  EMPTY_EMAIL: "Enter Your E-Mail",
  VALID_EMAIL: "Enter Valid Email",
  EMPTY_PASSWORD: "Enter Your Password",
  EMAILADDRESS: "Email Address",
  ISVALID: "please enter your email",
  ENTER_OTP: "Enter Your Otp Code",
  REMEMBER_ME: "Remember me",
  TYPE_TEXT: "text",
  TYPE_NUMBER: "number",
  TYPE_FILE: "file",
  TYPE_SELECT: "select",
  TYPE_ZIP: "zip",
  TYPE_TEL: "tel",
  TYPE_URL: "url",
  TYPE_MONTH: "month",
  TYPE_SUBMIT: "Submit",
  TYPE_CANCEL: "Cancel",
  FIELD_SIZE: "small",
  MARGIN: "normal",
  TYPE_EMAIL: "email",
  ORG_MSG: "Organization created Successfully",
  IMG_MSG: "Image uploaded Successfully",
  CONFIRM_MSG: "Are you sure you want to leave this page?",
  STEP_1: "Create Organization ",
  STEP_2: "Select Departments & Designations",
  STEP_WARNING: "You can't skip a step that isn't optional.",
  STEP_HEADING: "All steps completed - you&apos;re finished",
  BTN_NEXT: "Next",
  BTN_BACK: "Back",
  BTN_SKIP: "Skip",
  DEPARTMENT_HEADING: "Department",
  DEPARTMENT_HEADING_2: "Add Departments",
  DESIGNATION_HEADING: "Designation",
  ADD_DEPARTMENT: "Add New Department",
  ADD_DESIGNATION: "Add New Designation",
  DEP_NAME: "Department Name",
  DES_NAME: "Designation Name",
  DES_NEW_HEADING: "Select Department and Add new Designation",

  FORGOT_PASSWORD: "Forgot Password",
  SUBMIT: "Submit",
  VERIFY: "Verify",
  RESET_PASSWORD: "Reset Password",
  REGISTER_BTN: "Register",
  RESET_BTN: "Rest Password",
  SIGN_IN: "Sign In",
  CREATE_ORG: "organizationcreation",
  JOB_HUNTER: "Job Hunter",
  CREATE_JOB: "jobhunter",
  PLEASE_WAIT: "Please Wait...",
  ACCEPT_POLICY:
    " I agree that I've read and agreed to the  <Link> Terms & Conditions </Link> and Privacy Policy.",
  RESEND_OTP: "Resend Otp",
  ADD_EMPLOYEE: "ADD EMPLOYEE",

  ADDITIONAL: "Additional Charges & Restrictions",
  SELECT_EMPLOYEE: "Select Employee",
  SELECT_CHARGE: "Select Charges or Restrictions",
  PERMISSION: "Permission",
  CREATE: "Create",
  EDIT: "Edit",
  READ: "Read",
  UPDATE: "Update",
  DELETE: "Delete",

  TITLE: "Enter Job Title",
  JOB_CREATE: "Create job",
  ENTER_FORM_DATA: "Enter Your Job Details",
  DESIGNATION: "Enter Job Designation",
  COMPANY_NAME: "Enter Company Name",
  SALARY_RANGE: "Salary Range",
  SALARY_RANGE_MIN: "Enter Salary Range Min",
  SALARY_RANGE_MAX: "Enter Salary Range Max",
  JOB_REQUIREMENTS: "Enter Job Requirement & Responsibilites",
  JOB_RESBONSIBILITIES: "Enter Job Responsibilities",
  EDIT_JOB: "Edit Job Details",
  SELECT_DEPARTMENT: "Select Department",
  SELECT_DESIGNATION: "Select Designation",
};
